CURRENT_STRIPE_PUBLISHABLE_KEY = ENV["HEROKU_ENV"] == 'production' ? ENV["STRIPE_PUBLISHABLE_KEY"] : ENV["STRIPE_TEST_PUBLISHABLE_KEY"]

CURRENT_STRIPE_SECRET_KEY = ENV["HEROKU_ENV"] == 'production' ? ENV["STRIPE_SECRET_KEY"] : ENV["STRIPE_TEST_SECRET_KEY"]